# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"

# Whitelisting branches
branches:
  only:
    - master

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements/test.txt
# preparation command

before_script:
  - cd colegend
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# command to run tests, e.g. python setup.py test
script:  coverage run manage.py test --settings=configuration.settings.test

services:
  - selenium

after_script:
  - "/etc/init.d/xvfb stop"

after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
