# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"

# Whitelisting branches
branches:
  only:
    - master

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements/test.txt --use-mirrors
# preparation command

before_script:
  - cd colegend

# command to run tests, e.g. python setup.py test
script:  coverage run manage.py test --settings=configuration.settings.test

after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
